version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    networks:
      - app_net

  api:
    container_name: api
    image: prostokosmos/test-server
    platform: linux/amd64
    command: sh -c "sleep 10s && npx prisma migrate deploy && node ./dist/main.js"
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT:-3000}
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db
    networks:
      - app_net

  ui:
    container_name: ui
    image: prostokosmos/test-ui
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app_net

  nginx:
    container_name: nginx
    image: nginx
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - api
      - ui
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    platform: linux/amd64
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-qwerty}
      - SCRIPT_NAME=/pgadmin
    depends_on:
      - db
    networks:
      - app_net

networks:
 app_net:
   driver: bridge
